/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class itesm_gvision_apps_calibrator_CalibratorOCV */

#ifndef _Included_itesm_gvision_apps_calibrator_CalibratorOCV
#define _Included_itesm_gvision_apps_calibrator_CalibratorOCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    initOCVCalibrator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_initOCVCalibrator
  (JNIEnv *, jobject);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    findCorners
 * Signature: ([III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_findCorners
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    addCalibrationImage
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_addCalibrationImage
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    calibrate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_calibrate
  (JNIEnv *, jobject);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    getResults
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_getResults
  (JNIEnv *, jobject);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    getUndistortedImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_getUndistortedImage
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     itesm_gvision_apps_calibrator_CalibratorOCV
 * Method:    getHomographyMatrix
 * Signature: ([D[DIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_itesm_gvision_apps_calibrator_CalibratorOCV_getHomographyMatrix
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
