/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufabc_bassani_gpusurf_JavaGPUSurf */

#ifndef _Included_br_ufabc_bassani_gpusurf_JavaGPUSurf
#define _Included_br_ufabc_bassani_gpusurf_JavaGPUSurf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufabc_bassani_gpusurf_JavaGPUSurf
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_br_ufabc_bassani_gpusurf_JavaGPUSurf_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     br_ufabc_bassani_gpusurf_JavaGPUSurf
 * Method:    getFeatures
 * Signature: (Ljava/lang/String;[CF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_br_ufabc_bassani_gpusurf_JavaGPUSurf_getFeatures
  (JNIEnv *, jobject, jstring, jcharArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
